Repository SEKOIA-IO/automation-library, pull requests merged in 2023-07, with the labels that each got.

#12 Trellix edr
  Trellix/.gitignore
  Trellix/CHANGELOG.md
  Trellix/Dockerfile
  Trellix/client/__init__.py
  Trellix/client/http_client.py
  Trellix/client/schemas/__init__.py
  Trellix/client/schemas/attributes/__init__.py
  Trellix/client/schemas/attributes/epo_events.py
  Trellix/client/schemas/edr.py
  Trellix/client/schemas/token.py
  Trellix/client/token_refresher.py
  Trellix/logger/__init__.py
  Trellix/logger/config.py
  Trellix/logger/formatters.py
  Trellix/logger/handlers.py
  Trellix/main.py
  Trellix/manifest.json
  Trellix/poetry.lock
  Trellix/pyproject.toml
  Trellix/tests/__init__.py
  Trellix/tests/client/__init__.py
  Trellix/tests/client/schemas/__init__.py
  Trellix/tests/client/schemas/test_epo.py
  Trellix/tests/client/schemas/test_token.py
  Trellix/tests/client/test_http_client.py
  Trellix/tests/client/test_token_refresher.py
  Trellix/tests/conftest.py
  Trellix/tests/logger/__init__.py
  Trellix/tests/logger/test_config.py
  Trellix/tests/logger/test_formatters.py
  Trellix/tests/logger/test_handler.py
  Trellix/tests/trellix/__init__.py
  Trellix/tests/trellix/test_connector.py
  Trellix/trellix/__init__.py
  Trellix/trellix/connector.py
  Trellix/trellix/metrics.py
  Trellix/trigger_trellix_epo.json
Labels: wontfix

#108 Trellix: Update manifests
  Trellix/CHANGELOG.md
  Trellix/manifest.json
  Trellix/trigger_trellix_epo.json
Labels: enhancement

#109 Jumpcloud: switch to beta
  Jumpcloud/CHANGELOG.md
  Jumpcloud/manifest.json
  Jumpcloud/trigger_jumpclouddirectoryinsightsconnector.json
Labels: enhancement

#112 AWS: define aws_secret_access_key as a secret
  AWS/aws/base.py
  AWS/manifest.json
Labels: bug

#136 Sophos: add BETA Flag
  Sophos/CHANGELOG.md
  Sophos/manifest.json
  Sophos/trigger_sophos_xdr_query.json
Labels: enhancement

#137 Darktrace: add beta flag
  Darktrace/CHANGELOG.md
  Darktrace/manifest.json
  Darktrace/trigger_threat_visualizer_log.json
Labels: enhancement

#139 Saleforces: add beta flag
  Salesforce/CHANGELOG.md
  Salesforce/manifest.json
  Salesforce/trigger_salesforce_events.json
Labels: enhancement

#130 Sophos: Change the way to handle exceptions in the EDR connector
  Sophos/CHANGELOG.md
  Sophos/manifest.json
  Sophos/sophos_module/trigger_sophos_edr_events.py
Labels: bug

#145 Okta: ensure we save the progression
  Okta/CHANGELOG.md
  Okta/manifest.json
  Okta/okta_modules/system_log_trigger.py
Labels: bug

#123 Netskope: improve observability
  Netskope/manifest.json
  Netskope/netskope_modules/connector_pull_events_v2.py
  Netskope/netskope_modules/metrics.py
  Netskope/tests/test_pull_events_v2_connector.py
Labels: enhancement

#122 Connectors Observability
  CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
  CrowdStrikeFalcon/crowdstrike_falcon/metrics.py
  CrowdStrikeFalcon/manifest.json
  Cybereason/cybereason_modules/connector_pull_events.py
  Cybereason/cybereason_modules/metrics.py
  Cybereason/manifest.json
  Cybereason/tests/test_pull_events_connector.py
  Darktrace/darktrace_modules/metrics.py
  Darktrace/darktrace_modules/threat_visualizer_log_trigger.py
  Darktrace/tests/test_threat_visualizer_log_trigger.py
  Github/github_modules/audit_log_trigger.py
  Github/github_modules/metrics.py
  Github/manifest.json
  Github/tests/test_audit_log_trigger.py
  Google/google_module/pubsub.py
  Google/manifest.json
  Office365/manifest.json
  Office365/office365/message_trace/base.py
  Office365/office365/metrics.py
  Okta/okta_modules/metrics.py
  Okta/okta_modules/system_log_trigger.py
  Proofpoint/manifest.json
  Proofpoint/proofpoint_modules/trigger_pod_events.py
  Proofpoint/proofpoint_modules/trigger_tap_events.py
  SkyhighSecurity/gateway_cloud_services/trigger_skyhigh_security_swg.py
  SkyhighSecurity/manifest.json
  Sophos/CHANGELOG.md
  Sophos/manifest.json
  Sophos/sophos_module/metrics.py
  Sophos/sophos_module/trigger_sophos_edr_events.py
  Tehtris/manifest.json
  Tehtris/tehtris_modules/metrics.py
  Tehtris/tehtris_modules/trigger_tehtris_events.py
  WithSecure/manifest.json
  WithSecure/withsecure/metrics.py
  WithSecure/withsecure/security_events_connector.py
Labels: enhancement

#111 JumpCloud: define api_key as a secret
  Jumpcloud/jumpcloud_modules/models.py
  Jumpcloud/manifest.json
Labels: bug
