Repository SEKOIA-IO/automation-library, pull requests merged in 2024-08, with the labels that each got.

#1060 Remove need for a configuration for Sekoia modules
  Sekoia.io/CHANGELOG.md
  Sekoia.io/manifest.json
Labels: enhancement

#1062 Netskope: handle when failing to decode the incoming message
  Netskope/CHANGELOG.md
  Netskope/manifest.json
  Netskope/netskope_modules/connector_pubsub_lite.py
  Netskope/netskope_modules/logging.py
  Netskope/poetry.lock
  Netskope/pyproject.toml
  Netskope/tests/test_pubsub_lite.py
Labels: bug

#1059 Azure & AWS: add two new metrics to monitor events lag
  AWS/CHANGELOG.md
  AWS/connectors/__init__.py
  AWS/connectors/metrics.py
  AWS/manifest.json
  Azure/CHANGELOG.md
  Azure/connectors/azure_eventhub.py
  Azure/connectors/metrics.py
  Azure/manifest.json
Labels: enhancement

#1065 Sophos: Adjust the rate-limiters
  Sophos/CHANGELOG.md
  Sophos/manifest.json
  Sophos/sophos_module/client/__init__.py
Labels: bug

#1067 SentinelOne: change logs and handle exception
  SentinelOne/CHANGELOG.md
  SentinelOne/manifest.json
  SentinelOne/poetry.lock
  SentinelOne/pyproject.toml
  SentinelOne/sentinelone_module/logging.py
  SentinelOne/sentinelone_module/logs/connector.py
  SentinelOne/tests/conftest.py
Labels: enhancement

#1068 SentinelOne: Fix the usage of the cursor in the connector
  SentinelOne/CHANGELOG.md
  SentinelOne/manifest.json
  SentinelOne/sentinelone_module/logs/connector.py
  SentinelOne/sentinelone_module/logs/helpers.py
  SentinelOne/tests/logs/test_connector.py
  SentinelOne/tests/logs/test_helpers.py
Labels: bug, enhancement

#1069 Trellix: fix Metrics
  Trellix/CHANGELOG.md
  Trellix/connectors/metrics.py
  Trellix/manifest.json
Labels: bug

#1072 SentinelOne: filter collected events
  SentinelOne/CHANGELOG.md
  SentinelOne/manifest.json
  SentinelOne/poetry.lock
  SentinelOne/pyproject.toml
  SentinelOne/sentinelone_module/logs/connector.py
  SentinelOne/sentinelone_module/logs/helpers.py
  SentinelOne/tests/logs/test_connector.py
  SentinelOne/tests/logs/test_helpers.py
Labels: bug

#1079 SentinelOne: fix connector
  SentinelOne/CHANGELOG.md
  SentinelOne/manifest.json
  SentinelOne/sentinelone_module/logs/connector.py
  SentinelOne/tests/conftest.py
  SentinelOne/tests/logs/test_connector.py
Labels: bug

#1080 CrowdStrikeFalcon: prevent events collect failure when the verticles collector authentication fails
  CrowdStrikeFalcon/CHANGELOG.md
  CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
  CrowdStrikeFalcon/manifest.json
  CrowdStrikeFalcon/tests/test_event_stream_trigger.py
Labels: bug

#1081 SentinelOne: change the name of the connectors
  SentinelOne/CHANGELOG.md
  SentinelOne/connector_sentinelone_deepvisibility.json
  SentinelOne/connector_sentinelone_logs.json
  SentinelOne/manifest.json
Labels: enhancement

#1082 SentinelOne: change triggers' name
  SentinelOne/CHANGELOG.md
  SentinelOne/manifest.json
  SentinelOne/trigger_sentinelone_deepvisibility.json
  SentinelOne/trigger_sentinelone_logs.json
Labels: enhancement
