Repository SEKOIA-IO/automation-library, pull requests merged in 2024-05, with the labels that each got.

#939 Add exponential backoff retry on WithSecure Auth API
  WithSecure/CHANGELOG.md
  WithSecure/manifest.json
  WithSecure/pyproject.toml
  WithSecure/tests/client/test_auth.py
  WithSecure/withsecure/client/auth.py
  WithSecure/withsecure/constants.py
Labels: enhancement

#949 WithSecure: Improve the resiliency of the connector
  WithSecure/CHANGELOG.md
  WithSecure/manifest.json
  WithSecure/poetry.lock
  WithSecure/pyproject.toml
  WithSecure/tests/test_helpers.py
  WithSecure/withsecure/helpers.py
  WithSecure/withsecure/security_events_connector.py
Labels: bug, enhancement

#950 AWS: add metric for collected events
  AWS/CHANGELOG.md
  AWS/connectors/metrics.py
  AWS/connectors/s3/__init__.py
  AWS/manifest.json
Labels: enhancement

#952 AWS: fix metric
  AWS/CHANGELOG.md
  AWS/connectors/s3/__init__.py
  AWS/manifest.json
Labels: bug

#951 S1DV: add a metric to count the number of discarded events
  SentinelOneDeepVisibility/CHANGELOG.md
  SentinelOneDeepVisibility/deep_visibility/connector_s3_logs.py
  SentinelOneDeepVisibility/deep_visibility/metrics.py
  SentinelOneDeepVisibility/manifest.json
Labels: enhancement

#958 Connectors: fix configuration
  Office365/CHANGELOG.md
  Office365/connector_office365_management_activity_api.json
  Office365/manifest.json
  Retarus/CHANGELOG.md
  Retarus/connector_retarus_events.json
  Retarus/manifest.json
Labels: bug
